# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/big-data/project/air/urp/fineLanding/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/big-data/project/air/urp/fineLanding

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/big-data/project/air/urp/fineLanding/CMakeFiles /media/big-data/project/air/urp/fineLanding//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/big-data/project/air/urp/fineLanding/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named finelanding

# Build rule for target.
finelanding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 finelanding
.PHONY : finelanding

# fast build rule for target.
finelanding/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/build
.PHONY : finelanding/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main.cpp.s
.PHONY : main.cpp.s

main/config.o: main/config.cpp.o
.PHONY : main/config.o

# target to build an object file
main/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/config.cpp.o
.PHONY : main/config.cpp.o

main/config.i: main/config.cpp.i
.PHONY : main/config.i

# target to preprocess a source file
main/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/config.cpp.i
.PHONY : main/config.cpp.i

main/config.s: main/config.cpp.s
.PHONY : main/config.s

# target to generate assembly for a file
main/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/config.cpp.s
.PHONY : main/config.cpp.s

main/controller.o: main/controller.cpp.o
.PHONY : main/controller.o

# target to build an object file
main/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/controller.cpp.o
.PHONY : main/controller.cpp.o

main/controller.i: main/controller.cpp.i
.PHONY : main/controller.i

# target to preprocess a source file
main/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/controller.cpp.i
.PHONY : main/controller.cpp.i

main/controller.s: main/controller.cpp.s
.PHONY : main/controller.s

# target to generate assembly for a file
main/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/controller.cpp.s
.PHONY : main/controller.cpp.s

main/math.o: main/math.cpp.o
.PHONY : main/math.o

# target to build an object file
main/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/math.cpp.o
.PHONY : main/math.cpp.o

main/math.i: main/math.cpp.i
.PHONY : main/math.i

# target to preprocess a source file
main/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/math.cpp.i
.PHONY : main/math.cpp.i

main/math.s: main/math.cpp.s
.PHONY : main/math.s

# target to generate assembly for a file
main/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/math.cpp.s
.PHONY : main/math.cpp.s

main/message.o: main/message.cpp.o
.PHONY : main/message.o

# target to build an object file
main/message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/message.cpp.o
.PHONY : main/message.cpp.o

main/message.i: main/message.cpp.i
.PHONY : main/message.i

# target to preprocess a source file
main/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/message.cpp.i
.PHONY : main/message.cpp.i

main/message.s: main/message.cpp.s
.PHONY : main/message.s

# target to generate assembly for a file
main/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/message.cpp.s
.PHONY : main/message.cpp.s

main/position.o: main/position.cpp.o
.PHONY : main/position.o

# target to build an object file
main/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/position.cpp.o
.PHONY : main/position.cpp.o

main/position.i: main/position.cpp.i
.PHONY : main/position.i

# target to preprocess a source file
main/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/position.cpp.i
.PHONY : main/position.cpp.i

main/position.s: main/position.cpp.s
.PHONY : main/position.s

# target to generate assembly for a file
main/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/finelanding.dir/build.make CMakeFiles/finelanding.dir/main/position.cpp.s
.PHONY : main/position.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... finelanding"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main/config.o"
	@echo "... main/config.i"
	@echo "... main/config.s"
	@echo "... main/controller.o"
	@echo "... main/controller.i"
	@echo "... main/controller.s"
	@echo "... main/math.o"
	@echo "... main/math.i"
	@echo "... main/math.s"
	@echo "... main/message.o"
	@echo "... main/message.i"
	@echo "... main/message.s"
	@echo "... main/position.o"
	@echo "... main/position.i"
	@echo "... main/position.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

